apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gatekeeper-config-policy-binding.yaml
- gatekeeper-config-policy.yaml
- required-annotations/required-annotations-policy.yaml