apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gatekeeper-policy
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-operator
          namespace: rhacm-policies
        spec:
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: gatekeeper
                  namespace: openshift-operators
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: gatekeeper-operator-product
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gatekeeper-config
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-config
          namespace: rhacm-policies
        spec:
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: operator.gatekeeper.sh/v1alpha1
                kind: Gatekeeper
                metadata:
                  name: gatekeeper
                  namespace: openshift-gatekeeper-system
                spec:
                  config:
                    matches:
                      - excludedNamespaces:
                          - open-cluster-management
                          - kube-*
                          - openshift-*
                          - openshift
                          - klusterlet-*
                          - hypershift
                          - open-*
                          - hive
                          - local-*
                          - multicluster-*
                          - rhacs-*
                          - stackrox
                          - cluster-*
                          - cert-manager*
                        processes:
                          - '*'
                  validatingWebhook: Enabled